Repository Peel-Organisation/Peel_API, pull requests merged in 2023-12, with the labels that each got.

#39 Update sh script
  script/crontab.sh
  script/crontab_dev.sh
  script/pull_deploy_docker-api-dev.sh
  script/pull_deploy_docker.sh
Labels: feature

#40 fix(frontend): fix algo
  src/controllers/match.controller.js
Labels: enhancement

#42 Update request log on API
  src/app.js
Labels: bug

#43 Update Logs
  src/app.js
Labels: bug

#44 Add security and ip tracability
  package.json
  src/app.js
Labels: feature

#48 Fix Match Controller - populate interest
  src/controllers/match.controller.js
Labels: feature
